// Datos de eventos de ExpoVital
const EVENTOS_DATA = {
    eventos: [
        {
            id: 1,
            titulo: "Aromaterapia para el Estrés",
            categoria: "belleza",
            categoriaTexto: "Belleza",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "Biotecgen",
            descripcion: "Técnicas de aromaterapia para reducir el estrés y mejorar el bienestar emocional.",
            hora: "11:00 am - 12:00 p.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Salón Wellness",
            esHoy: true,
            destacado: true
        },
        {
            id: 2,
            titulo: "Rutinas de Skincare Natural",
            categoria: "belleza",
            categoriaTexto: "Belleza",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "DermaNatural",
            descripcion: "Aprende a crear rutinas de cuidado facial con ingredientes naturales y productos orgánicos.",
            hora: "2:00 pm - 3:30 p.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Salón Beauty",
            esHoy: true,
            destacado: false
        },
        {
            id: 3,
            titulo: "Yoga y Meditación",
            categoria: "bienestar",
            categoriaTexto: "Bienestar",
            tipo: "masterclass",
            tipoTexto: "Masterclass",
            presentador: "Zentro Wellness",
            descripcion: "Sesión de yoga y meditación para encontrar el equilibrio entre cuerpo y mente.",
            hora: "9:00 am - 10:30 a.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Salón Zen",
            esHoy: true,
            destacado: false
        },
        {
            id: 4,
            titulo: "Nutrición Deportiva",
            categoria: "fitness",
            categoriaTexto: "Fitness",
            tipo: "conferencia",
            tipoTexto: "Conferencia",
            presentador: "Dr. Carlos Méndez",
            descripcion: "Conferencia sobre la importancia de la nutrición en el rendimiento deportivo y la recuperación.",
            hora: "4:00 pm - 5:00 p.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Auditorio Principal",
            esHoy: true,
            destacado: false
        },
        {
            id: 5,
            titulo: "Maquillaje Profesional",
            categoria: "belleza",
            categoriaTexto: "Belleza",
            tipo: "demostracion",
            tipoTexto: "Demostración",
            presentador: "Make Up Studio",
            descripcion: "Demostración de técnicas profesionales de maquillaje para diferentes ocasiones.",
            hora: "10:00 am - 11:30 a.m.",
            fecha: "2024-09-25",
            fechaTexto: "25 de septiembre",
            ubicacion: "Estudio de Belleza",
            esHoy: false,
            destacado: false
        },
        {
            id: 6,
            titulo: "Entrenamiento Funcional",
            categoria: "fitness",
            categoriaTexto: "Fitness",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "FitTraining Pro",
            descripcion: "Aprende ejercicios funcionales que puedes hacer en casa para mantenerte en forma.",
            hora: "3:00 pm - 4:30 p.m.",
            fecha: "2024-09-25",
            fechaTexto: "25 de septiembre",
            ubicacion: "Zona Fitness",
            esHoy: false,
            destacado: false
        },
        {
            id: 7,
            titulo: "Medicina Estética Avanzada",
            categoria: "salud",
            categoriaTexto: "Salud",
            tipo: "conferencia",
            tipoTexto: "Conferencia",
            presentador: "Dra. Ana Rodríguez",
            descripcion: "Últimas tendencias en medicina estética y tratamientos no invasivos para el rejuvenecimiento.",
            hora: "11:00 am - 12:30 p.m.",
            fecha: "2024-09-25",
            fechaTexto: "25 de septiembre",
            ubicacion: "Sala Médica",
            esHoy: false,
            destacado: false
        },
        {
            id: 8,
            titulo: "Terapias de Relajación",
            categoria: "bienestar",
            categoriaTexto: "Bienestar",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "SpaVital",
            descripcion: "Técnicas de relajación y manejo del estrés para mejorar la calidad de vida.",
            hora: "1:00 pm - 2:30 p.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Salón Relax",
            esHoy: false,
            destacado: false
        },
        {
            id: 9,
            titulo: "Cuidado Capilar Integral",
            categoria: "belleza",
            categoriaTexto: "Belleza",
            tipo: "masterclass",
            tipoTexto: "Masterclass",
            presentador: "Hair Expert",
            descripcion: "Masterclass sobre cuidado capilar, tratamientos y productos para diferentes tipos de cabello.",
            hora: "10:00 am - 11:30 a.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Salón Capilar",
            esHoy: false,
            destacado: false
        },
        {
            id: 10,
            titulo: "Diagnóstico Nutricional Personalizado",
            categoria: "salud",
            categoriaTexto: "Salud",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "Dra. María González",
            descripcion: "Aprende a evaluar tu estado nutricional y crear un plan alimentario personalizado.",
            hora: "5:00 pm - 6:30 p.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Laboratorio Nutricional",
            esHoy: true,
            destacado: false
        },
        {
            id: 11,
            titulo: "Rehabilitación Física Post-Lesión",
            categoria: "salud",
            categoriaTexto: "Salud",
            tipo: "demostracion",
            tipoTexto: "Demostración",
            presentador: "Fisioterapia Vital",
            descripcion: "Demostración de técnicas de rehabilitación para lesiones deportivas comunes.",
            hora: "12:30 pm - 1:30 p.m.",
            fecha: "2024-09-25",
            fechaTexto: "25 de septiembre",
            ubicacion: "Centro de Rehabilitación",
            esHoy: false,
            destacado: false
        },
        {
            id: 12,
            titulo: "Crossfit para Principiantes",
            categoria: "fitness",
            categoriaTexto: "Fitness",
            tipo: "masterclass",
            tipoTexto: "Masterclass",
            presentador: "CrossVital Gym",
            descripcion: "Introducción al crossfit con ejercicios básicos y técnicas de seguridad.",
            hora: "6:00 am - 7:30 a.m.",
            fecha: "2024-09-25",
            fechaTexto: "25 de septiembre",
            ubicacion: "Box de Crossfit",
            esHoy: false,
            destacado: false
        },
        {
            id: 13,
            titulo: "Mindfulness y Reducción del Estrés",
            categoria: "bienestar",
            categoriaTexto: "Bienestar",
            tipo: "conferencia",
            tipoTexto: "Conferencia",
            presentador: "Centro Mindfulness",
            descripcion: "Conferencia sobre técnicas de mindfulness para el manejo del estrés diario.",
            hora: "7:00 pm - 8:00 p.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Auditorio Zen",
            esHoy: false,
            destacado: false
        },
        {
            id: 14,
            titulo: "Tratamientos Faciales Avanzados",
            categoria: "belleza",
            categoriaTexto: "Belleza",
            tipo: "conferencia",
            tipoTexto: "Conferencia",
            presentador: "Dr. Roberto Silva",
            descripcion: "Últimas innovaciones en tratamientos faciales no invasivos y antienvejecimiento.",
            hora: "3:30 pm - 4:30 p.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Sala de Estética",
            esHoy: false,
            destacado: false
        },
        {
            id: 15,
            titulo: "Pilates Terapéutico",
            categoria: "fitness",
            categoriaTexto: "Fitness",
            tipo: "demostracion",
            tipoTexto: "Demostración",
            presentador: "Studio Pilates+",
            descripcion: "Demostración de ejercicios de pilates para rehabilitación y fortalecimiento.",
            hora: "8:00 am - 9:00 a.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Estudio de Pilates",
            esHoy: false,
            destacado: false
        },
        {
            id: 16,
            titulo: "Medicina Preventiva del Siglo XXI",
            categoria: "salud",
            categoriaTexto: "Salud",
            tipo: "masterclass",
            tipoTexto: "Masterclass",
            presentador: "Instituto de Medicina Preventiva",
            descripcion: "Masterclass sobre nuevas tendencias en medicina preventiva y diagnóstico temprano.",
            hora: "5:30 pm - 7:00 p.m.",
            fecha: "2024-09-26",
            fechaTexto: "26 de septiembre",
            ubicacion: "Auditorio Médico",
            esHoy: false,
            destacado: false
        },
        {
            id: 17,
            titulo: "Aqua Fitness Intensivo",
            categoria: "fitness",
            categoriaTexto: "Fitness",
            tipo: "taller",
            tipoTexto: "Taller",
            presentador: "AquaVital Center",
            descripcion: "Rutina intensiva de ejercicios acuáticos para quemar calorías y tonificar.",
            hora: "7:00 am - 8:30 a.m.",
            fecha: "2024-09-24",
            fechaTexto: "24 de septiembre",
            ubicacion: "Piscina Terapéutica",
            esHoy: true,
            destacado: false
        }
    ]
};